export {
    closePluginView,
    closePluginViewById,
    detachPluginView,
    executeResult,
    getCurrentSurfaceMetadata,
    getPluginViewDescriptor,
    getSettings,
    hideMainWindow,
    launcherPanel,
    openPluginDevtools,
    openPluginView,
    pinResult,
    reorderPinnedResults,
    resizeMainWindowHeight,
    revealInFileManager,
    startWindowDragging,
    unpinResult,
} from '@litools/plugin-core';
