fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .plugin(
                "litools-core",
                tauri_build::InlinedPlugin::new()
                    .commands(&[
                        "search",
                        "launcher_panel",
                        "pin_result",
                        "unpin_result",
                        "reorder_pinned_results",
                        "execute_result",
                        "detach_route",
                        "update_surface_route",
                        "list_windows",
                        "get_current_window_metadata",
                        "hide_window",
                        "focus_window",
                        "destroy_window",
                        "start_window_dragging",
                        "hide_main_window",
                        "show_main_window",
                        "focus_main_window",
                        "resize_main_window_height",
                        "reveal_in_file_manager",
                        "reload_index",
                        "get_diagnostics",
                        "get_settings",
                        "update_settings",
                        "list_plugins",
                        "get_plugin_view_descriptor",
                        "install_plugin",
                        "uninstall_plugin",
                        "toggle_plugin",
                        "open_plugin_view",
                        "hide_plugin_view",
                        "detach_plugin_view",
                        "close_plugin_view",
                        "close_plugin_view_by_id",
                        "get_plugin_view_info",
                        "open_plugin_devtools",
                    ])
                    .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
            )
            .plugin(
                "litools-sdk",
                tauri_build::InlinedPlugin::new()
                    .commands(&[
                        "sdk_runtime_ready",
                        "sdk_runtime_get_info",
                        "sdk_permissions_query",
                        "sdk_ui_close",
                        "sdk_ui_set_title",
                        "sdk_ui_toast",
                        "sdk_storage_get",
                        "sdk_storage_set",
                        "sdk_storage_remove",
                        "sdk_storage_clear",
                        "sdk_settings_get",
                        "sdk_settings_update",
                        "sdk_diagnostics_get",
                        "sdk_plugins_list",
                        "sdk_commands_add",
                        "sdk_commands_remove",
                        "sdk_commands_replace",
                        "sdk_commands_update",
                        "sdk_search_register_provider",
                        "sdk_search_unregister_provider",
                        "sdk_search_submit",
                    ])
                    .default_permission(tauri_build::DefaultPermissionRule::AllowAllCommands),
            ),
    )
    .unwrap();
}
